version: "3.9"
services:
  postgres:
    image: postgres:15.3
    container_name: "postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    command: postgres -p 5432
    ports: [
      "5432:5432"
    ]